services:
  influxdb:
      image: influxdb:latest
      ports:
        - 8086:8086
      volumes:
        - influxdb-storage:/var/lib/influxdb

  influxdb_setup:
    image: influxdb:latest
    command:
      - /bin/sh
      - -c
      - |
        influx setup --bucket temperatur_bucket -t temperature_token -o 42clue --username=admin --password=admin123 --host=http://influxdb:8086 -f
    restart: on-failure:15

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    ports:
      - 3000:3000
    depends_on:
      - influxdb
    volumes:
      - grafana-storage:/var/lib/grafana
      
volumes:
  influxdb-storage:
  grafana-storage:
